# Generated by Django 5.0.6 on 2024-07-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('guests', models.IntegerField(verbose_name='Huéspedes')),
                ('message', models.TextField(verbose_name='mensaje')),
            ],
        ),
    ]
